module.exports = [
  {
    source_name: "Staff Selection Commission",
    source_code: "SSC",
    base_url: "https://ssc.gov.in",
    notification_url: "https://ssc.gov.in/api/noticeBoard/getAllNoticeBoard?page=0&pageSize=20&noticeBoardType=all",
    result_url: "https://ssc.gov.in/home/notice-board",
    admit_card_url: "https://ssc.gov.in/home/notice-board",
    answer_key_url: "https://ssc.gov.in/home/notice-board",
    fetch_type: "api",
    status: "active",
  },
  {
    source_name: "Union Public Service Commission",
    source_code: "UPSC",
    base_url: "https://upsc.gov.in",
    notification_url: "https://upsc.gov.in/whats-new",
    result_url: "https://upsc.gov.in/whats-new",
    admit_card_url: "https://upsc.gov.in/whats-new",
    answer_key_url: "https://upsc.gov.in/whats-new",
    fetch_type: "html",
    status: "active",
  },
  {
    source_name: "Railway Recruitment Board",
    source_code: "RRB",
    base_url: "https://indianrailways.gov.in",
    notification_url: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,533,2015",
    result_url: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,533,2015",
    admit_card_url: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,533,2015",
    answer_key_url: "https://indianrailways.gov.in/railwayboard/view_section.jsp?lang=0&id=0,1,304,366,533,2015",
    fetch_type: "html",
    status: "active",
  },
  {
    source_name: "Institute of Banking Personnel Selection",
    source_code: "IBPS",
    base_url: "https://www.ibps.in",
    notification_url: "https://www.ibps.in/",
    result_url: "https://www.ibps.in/",
    admit_card_url: "https://www.ibps.in/",
    answer_key_url: "https://www.ibps.in/",
    fetch_type: "html",
    status: "active",
  },
];
